sudo: required

services:
  - mongodb
  - redis
  - docker

language: go
go: "1.10"

before_install:
  # setup some env variables
  - GO_FILES=$(find . -iname '*.go' )  # All the .go files

  # setup dependency management tool
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

  # install linters
  - go get -u github.com/golang/lint/golint     # Linter
  - go get -u github.com/kisielk/errcheck       # errcheck checks that you checked errors.

  # docker services
  - docker run -d -p 1883:1883 eclipse-mosquitto

install:
  - dep ensure

script:
  - go vet -v $PKGS                   # go vet is the official Go static analyzer
  - errcheck -exclude errcheck_excludes.txt -verbose $PKGS           # Check for unchecked errors
  - golint -set_exit_status $PKGS     # One last linter
  - go test -v $PKGS                  # Run all the tests
